name: Bastion

on:
  push:
    branches: [dev]
    paths:
      - 'packer/**'
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
      
      - name: Check if Packer is installed
        id: check-packer
        run: |
              if ! command -v packer &> /dev/null
              then
                echo "Packer is not installed. Proceeding with installation."
                wget https://releases.hashicorp.com/packer/1.7.6/packer_1.7.6_linux_amd64.zip
                unzip -o packer_1.7.6_linux_amd64.zip
                sudo mv packer /usr/local/bin/
              else
                echo "Packer is already installed."
              fi

      - name: Initialize Packer build
        run: |
          cd packer/bastion
          packer init aws-ubuntu-bastion.pkr.hcl

      - name: Build AMI with Packer
        run: |
          cd packer/bastion
          packer build aws-ubuntu-bastion.pkr.hcl

  deploy-bastion:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: success()

    container:
      image: georgeulahannan/terraform:07
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

      - name: Terraform Bastion Plan
        id: bastion_plan
        run: |
          cd tfscaffold
          ./bin/terraform.sh -p codeblue -c bastion -e ${{ steps.get_branch.outputs.branch_name }} -r us-east-1 -a plan

      - name: Terraform Bastion apply
        if: steps.bastion_plan.outcome == 'success'
        run: |
          cd tfscaffold
          ./bin/terraform.sh -p codeblue -c bastion -e ${{ steps.get_branch.outputs.branch_name }} -r us-east-1 -a apply
