name: Terraform

on:
  push:
    branches: [dev]

jobs:
  terraform:
    runs-on: ubuntu-latest

    container:
      image: georgeulahannan/terraform:07
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Print branch name
        shell: bash
        run: echo ${{ steps.extract_branch.outputs.branch }}

      # - name: Set Build Number Environment Variable
      #   run: |
      #     echo "BUILD_NUMBER=$((${{ github.run_number }}+${{ github.run_attempt }}))" >> $GITHUB_ENV
      #     echo $BUILD_NUMBER

      # - name: Increase build
      #   run: |
      #     echo "GITHUB_RUN_NUMBER_WITH_OFFSET=$(($GITHUB_RUN_NUMBER+1971))" >> $GITHUB_ENV
      #     echo $GITHUB_RUN_NUMBER_WITH_OFFSET

      - name: 'Set build id'
        id: build_id
        run: echo "id=$(date +%s)" >> $GITHUB_OUTPUT
        
      - name: 'Cache .build-id'
        uses: actions/cache@v4
        with:
          # store the build id to github cache
          path: ${{ github.workspace }}/.build-id
          # use the build id to generate a completly unique cache
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-${{ steps.build_id.outputs.id }}
      - name: 'Save build id'
        # store the build id to a folder that we can later cache.
        run: |
          mkdir -p .build-id
          echo $BUILD_ID 
          echo $BUILD_ID > .build-id/id

        env:
          BUILD_ID: ${{ steps.build_id.outputs.id }}
