name: Terraform

on:
  push:
    branches: [dev]
    paths:
      - 'tfscaffold/**'

jobs:
  generate_build_id:

    runs-on: ubuntu-latest

    outputs:
      build_id: ${{ steps.build_id.outputs.id }}
      branch: ${{ steps.extract_branch.outputs.branch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate build ID
        id: build_id
        run: echo "id=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

  terraform_fmt:
      needs: generate_build_id
      runs-on: ubuntu-latest
      container:
        image: hashicorp/terraform:1.8.5
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Run terraform fmt
          run: |
            cd tfscaffold
            terraform fmt -check -recursive components/ etc/
    
  tflint:
    needs: [generate_build_id, terraform_fmt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run TFLint on each component
        run: |
          cd tfscaffold/components

          # Initialize TFLint plugins once (assumes shared config at root)
          tflint --init --config ../.tflint.hcl

          # Loop through each module subdirectory and run TFLint
          for dir in */ ; do
            echo "Running TFLint in $dir..."
            tflint --chdir="$dir" --config ../.tflint.hcl || exit 1
          done


  checkov:
    needs: [generate_build_id,tflint]
    runs-on: ubuntu-latest
    container:
      image: bridgecrew/checkov:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        run: |
          cd tfscaffold/components/
          checkov -d . --skip-check CKV_TF* --skip-check CKV_AWS_*

  view_vpc_tf_plan_apply:
    needs: [generate_build_id,tflint,checkov]
    runs-on: ubuntu-latest

    container:
      image: georgeulahannan/terraform:07
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform VPC Show Plan
        id: vpc_plan_show
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c vpc \
            -r us-east-1 \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a show

      - name: Terraform VPC Plan to S3
        id: vpc_plan_upload_s3
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c vpc \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a plan

      - name: Terraform VPC Plan Apply
        id: vpc_plan_apply
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c vpc \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a apply

  view_acm_tf_plan_apply:
    needs: [generate_build_id,tflint,checkov,view_vpc_tf_plan_apply]
    runs-on: ubuntu-latest
    container:
      image: georgeulahannan/terraform:07
      options: --user root
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terraform ACM Show Plan
        id: acm_plan_show
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c acm \
            -r us-east-1 \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a show
    
      - name: Terraform ACM Plan to S3
        id: acm_plan_upload_s3
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c acm \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a plan

      - name: Terraform ACM Plan Apply
        id: acm_plan_apply
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c acm \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a apply
  
  view_alb_tf_plan_apply:
    needs: [generate_build_id,tflint,checkov,view_vpc_tf_plan_apply,view_acm_tf_plan_apply]
    runs-on: ubuntu-latest
    container:
      image: georgeulahannan/terraform:07
      options: --user root
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terraform ALB Show Plan
        id: alb_plan_show
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c alb \
            -r us-east-1 \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a show
    
      - name: Terraform ALB Plan to S3
        id: alb_plan_upload_s3
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c alb \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a plan

      - name: Terraform ALB Plan Apply
        id: alb_plan_apply
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c alb \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a apply

  view_eks_tf_plan_apply:
    needs: [generate_build_id,tflint,checkov,view_vpc_tf_plan_apply,view_alb_tf_plan_apply]
    runs-on: ubuntu-latest
    container:
      image: georgeulahannan/terraform:07
      options: --user root
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terraform EKS Show Plan
        id: eks_plan_show
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c eks \
            -r us-east-1 \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a show
    
      - name: Terraform EKS Plan to S3
        id: eks_plan_upload_s3
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c eks \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a plan

      - name: Terraform EKS Plan Apply
        id: eks_plan_apply
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c eks \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a apply

  view_addons_tf_plan_apply:
    needs: [generate_build_id,tflint,checkov,view_vpc_tf_plan_apply,view_eks_tf_plan_apply]
    runs-on: ubuntu-latest
    container:
      image: georgeulahannan/terraform:07
      options: --user root
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terraform EKS Addon packages Show Plan
        id: addons_plan_show
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c addons \
            -r us-east-1 \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a show
    
      - name: Terraform EKS Addon packages Plan to S3
        id: addons_plan_upload_s3
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c addons \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a plan

      - name: Terraform EKS Addon packages Plan Apply
        id: addons_plan_apply
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c addons \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a apply
  
  view_argocd_tf_plan_apply:
    needs: [generate_build_id,tflint,checkov,view_vpc_tf_plan_apply,view_eks_tf_plan_apply,view_addons_tf_plan_apply]
    runs-on: ubuntu-latest
    container:
      image: georgeulahannan/terraform:07
      options: --user root
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terraform ARGOCD packages Show Plan
        id: argocd_plan_show
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c argocd \
            -r us-east-1 \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a show
    
      - name: Terraform ARGOCD packages Plan to S3
        id: argocd_plan_upload_s3
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c argocd \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a plan

      - name: Terraform ARGOCD packages Plan Apply
        id: argocd_plan_apply
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c argocd \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a apply

  view_argocdapp_tf_plan_apply:
    needs: [generate_build_id,tflint,checkov,view_vpc_tf_plan_apply,view_eks_tf_plan_apply,view_addons_tf_plan_apply,view_argocd_tf_plan_apply]
    runs-on: ubuntu-latest
    container:
      image: georgeulahannan/terraform:07
      options: --user root
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terraform ARGOCD APP packages Show Plan
        id: argocdapp_plan_show
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c argocdapp \
            -r us-east-1 \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a show
    
      - name: Terraform ARGOCD packages Plan to S3
        id: argocdapp_plan_upload_s3
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c argocdapp \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a plan

      - name: Terraform ARGOCD APP Plan Apply
        id: argocdapp_plan_apply
        run: |
          cd tfscaffold
          ./bin/terraform.sh \
            -p codebule \
            -c argocdapp \
            -r us-east-1 \
            -i ${{ needs.generate_build_id.outputs.build_id }} \
            -e ${{ needs.generate_build_id.outputs.branch }} \
            -a apply