name: Terraform

on:
  push:
    branches: [dev]

jobs:
  terraform:
    runs-on: ubuntu-latest

    container:
      image: georgeulahannan/terraform:07
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Print branch name
        shell: bash
        run: echo ${{ steps.extract_branch.outputs.branch }}

      - uses: travisj/build-number-action@v1
        id: my-project-build-number
      
      - name: Echo Build Number
        run: echo $BUILD_NUMBER
        env:
          BUILD_NUMBER: ${{ steps.my-project-build-number.outputs.build-number }}